In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [3]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [4]:
text_test=["i am samraj","i love india"]
text_preocessed=bert_preprocess_model(text_test)

In [5]:
text_preocessed.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [6]:
text_preocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [7]:
bert_encoder_model = hub.KerasLayer(encoder_url)


In [10]:
text_result=bert_encoder_model(text_preocessed)


In [15]:
text_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [16]:
text_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.90905267, -0.43768942, -0.46207058, ..., -0.48330122,
        -0.72118896,  0.92192274],
       [-0.9305879 , -0.39886287, -0.54726136, ..., -0.24072902,
        -0.6662712 ,  0.9040463 ]], dtype=float32)>

In [17]:
text_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-1.1866006e-01,  5.8246922e-01, -9.7258583e-02, ...,
         -3.3045553e-02,  3.1129837e-01,  4.9712422e-01],
        [ 1.5277361e-02,  9.9350261e-03, -5.4490346e-01, ...,
          2.0262718e-02,  5.5941916e-01,  1.8848534e-01],
        [-4.1367409e-01,  5.2561767e-02,  1.1610420e-01, ...,
          2.6552647e-01,  5.7873428e-01,  3.1152323e-01],
        ...,
        [-1.1303812e-01, -2.9335300e-02,  5.5865031e-01, ...,
          3.2751432e-01,  3.7004463e-02, -6.6901008e-03],
        [-2.1482959e-01,  1.3828947e-01,  6.0950857e-01, ...,
          2.5584438e-01, -1.2393908e-01, -2.4831194e-01],
        [-4.6177900e-01, -1.9169638e-01,  4.3148968e-01, ...,
          3.4059501e-01, -1.9272812e-01, -3.2415652e-01]],

       [[-7.3014468e-02,  2.9683924e-01, -5.4883502e-02, ...,
         -5.7500046e-01,  2.6775628e-01,  2.6741537e-01],
        [ 3.5924789e-01,  9.2717087e-01, -2.7763340e-01, ...,
         -4.5328957e-01,  6.

In [19]:
text_result['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.18417045,  0.04666947, -0.11979195, ..., -0.03734184,
          0.14215276,  0.02411334],
        [ 0.77238137,  0.8891811 , -0.5108384 , ...,  0.5149803 ,
          0.86166555, -0.06011426],
        [-0.07264605,  0.12031516,  0.4447937 , ...,  0.16154078,
          1.56906   , -0.70398825],
        ...,
        [-0.01122512, -0.21315962,  0.61906064, ...,  0.4631499 ,
         -0.12799111,  0.01281444],
        [-0.09545104, -0.23591812,  0.4948591 , ...,  0.48006165,
         -0.02251821, -0.09355441],
        [ 0.05027047, -0.15729749,  0.52189595, ...,  0.83061534,
         -0.3318614 , -0.1968798 ]],

       [[ 0.15133615,  0.08122401, -0.09441697, ..., -0.00495034,
          0.15823336,  0.08329478],
        [ 0.64257145,  0.91123366, -0.20715523, ...,  0.40772444,
          0.7814262 ,  0.07786281],
        [ 1.5023903 ,  0.7790859 ,  0.22701085, ...,  0.57203805,
          0.85518026, -0.08478036],
        ...,

In [20]:
text_result['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-1.1866006e-01,  5.8246922e-01, -9.7258583e-02, ...,
         -3.3045553e-02,  3.1129837e-01,  4.9712422e-01],
        [ 1.5277361e-02,  9.9350261e-03, -5.4490346e-01, ...,
          2.0262718e-02,  5.5941916e-01,  1.8848534e-01],
        [-4.1367409e-01,  5.2561767e-02,  1.1610420e-01, ...,
          2.6552647e-01,  5.7873428e-01,  3.1152323e-01],
        ...,
        [-1.1303812e-01, -2.9335300e-02,  5.5865031e-01, ...,
          3.2751432e-01,  3.7004463e-02, -6.6901008e-03],
        [-2.1482959e-01,  1.3828947e-01,  6.0950857e-01, ...,
          2.5584438e-01, -1.2393908e-01, -2.4831194e-01],
        [-4.6177900e-01, -1.9169638e-01,  4.3148968e-01, ...,
          3.4059501e-01, -1.9272812e-01, -3.2415652e-01]],

       [[-7.3014468e-02,  2.9683924e-01, -5.4883502e-02, ...,
         -5.7500046e-01,  2.6775628e-01,  2.6741537e-01],
        [ 3.5924789e-01,  9.2717087e-01, -2.7763340e-01, ...,
         -4.5328957e-01,  6.